#!/bin/bash

version=${2:-latest}

case $1 in
  golangci-lint)
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@$version
    ;;

  gopls)
    go install golang.org/x/tools/gopls@$version
    ;;

  revive)
    go install github.com/mgechev/revive@$version
    ;;

  structslop)
    go install github.com/orijtech/structslop/cmd/structslop@$version
    ;;

  staticcheck)
    go install honnef.co/go/tools/cmd/staticcheck@$version
    ;;

  gotestsum)
    go install gotest.tools/gotestsum@$version
    ;;

  dlv)
    go install github.com/go-delve/delve/cmd/dlv@$version
    ;;

  gum)
    go install github.com/charmbracelet/gum@$version
    ;;

  *)
    echo "please provide executable to install"
    exit 1
    ;;
esac
