#!/bin/bash

case $1 in
  golangci-lint)
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    ;;

  gopls)
    go install golang.org/x/tools/gopls@latest
    ;;

  revive)
    go install github.com/mgechev/revive@latest
    ;;

  structslop)
    go install github.com/orijtech/structslop/cmd/structslop@latest
    ;;

  staticcheck)
    go install honnef.co/go/tools/cmd/staticcheck@latest
    ;;

  gotestsum)
    go install gotest.tools/gotestsum@latest
    ;;

  dlv)
    go install github.com/go-delve/delve/cmd/dlv@latest
    ;;

  gum)
    go install github.com/charmbracelet/gum@latest
    ;;

  *)
    echo "please provide executable to install"
    exit 1
    ;;
esac
